### ISSUE TITLE
Explanation of parameter self.pretrain_steps

### ISSUE THREAD

**Issue by Darcy103** [lufanma/IFR#1]
Thank you or your great work. I have two confusions:
1) I don't understand the meaning of **_self.pretrain_steps_**. Could you please explain?
2) Did you use the MDEQ method? (eg, apply the Implicit Feature Refinement to multi-resolution feature), but I feel as if DEQ is applied to the feature Pi (eg, P4) for this paper.
![question](https://user-images.githubusercontent.com/80041285/145831099-7ee3fd88-335d-4f67-93d4-2fd2c4c07d60.PNG)

**Comment by lufanma** [comment]
The "pretrain" strategy is adopted to stabilize the training process. In the initial "pretrain" phase, the input feature X and corresponding hidden feature are just fed to the weight-sharing repeat_block, following the unrolling process of implicit refinement module given in Eq.3 in the paper. After that, the IFR process starts.

Here, we just use the implicit feature refinement module to improve the single-resolution RoI feature or the down-sampled whole feature Pi in the head network. Of course, our method can also be extended to multi-scale features, like MDEQ.

**Comment by Darcy103** [comment]
thank you for your answer
